### ISSUE TITLE
Does not work on Xiaomi Redmi Note 8 (ginkgo)

### ISSUE THREAD

**Issue by roman82101** [TalkingPanda0/osram-remote#2]
Hello, LineageOS 18.1 firmware, when you click on a button in the application IR port lights up, but the bulb does not react. Bulb https://ww.aliexpress.us/item/2251832784210351.html

**Comment by TalkingPanda0** [comment]
This app was designed only for osram light bulbs but i have added a way to add other remotes you can find the codes for your bulb on the internet or by bruteforcing using the app
