### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [TalkingPanda0/osram-remote#3]
https://monitor.f-droid.org/builds/log/org.talkingpanda.osram_remote/3#site-footer Could you please take a look? Thanks!

**Comment by licaon-kter** [comment]
last flutter submodule update was 10 months ago... https://github.com/TalkingPanda0/osram-remote/tree/v1.2.1


disabled this version: https://gitlab.com/fdroid/fdroiddata/-/commit/db5c12714cdf17aa54d027ab2669d23ac479e3d0

**Comment by linsui** [comment]
It failed with a different error. https://gitlab.com/linsui/fdroiddata/-/jobs/5858301175

**Comment by licaon-kter** [comment]
@linsui and adding
```
│ android {                                                                   │
│   lintOptions {                                                             │
│     checkReleaseBuilds false                                                │
│   }                                                                         │
│ } 
```

as the text says does not help?

**Comment by linsui** [comment]
I guess not because that line has been added months ago.

**Comment by TalkingPanda0** [comment]
Deleting .pub-cache from scandelete and putting it into scanignore fixes the issue

**Comment by licaon-kter** [comment]
Well, why? Which file is needed that gets cleaned up by scandelete?

**Comment by TalkingPanda0** [comment]
It is deleting the file  .pub-cache/hosted/pub.dev/ir_sensor_plugin-0.3.0/android/libs/flutter.jar, which is the library i use for  transmitting IR.

**Comment by licaon-kter** [comment]
Well, as expected, binaries are not accepted (unless from trusted sources)

So, how can we build that?

**Comment by TalkingPanda0** [comment]
I have made the app not use that library.

**Comment by linsui** [comment]
Thanks!
